### ISSUE TITLE
Either GLIBC_2.23 not found (python 3.7) OR unable to open file: name = 'CNN.h5' (python 3.6) error thrown

### ISSUE THREAD

**Issue by robertzeibich** [wangruohan1995/SpliceFinder#4]
I am still trying to get the tool running. When I install the recommended packages (**python3.7**), I get the following error when the script test_Cla.py is called:

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_Cla.py", line 4, in <module>
    import keras
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
mv: cannot stat ‘CNN.h5’: No such file or directory
cp: cannot stat ‘fp_seq’: No such file or directory
cat: fp_seq: No such file or directory
cat: fp_seq: No such file or directory
Using TensorFlow backend.
Traceback (most recent call last):
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "CNN.py", line 4, in <module>
    import keras
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
```
Online I found that when using a different python version (**python3.6**), this error can be resolved, but now I am having another error and I do not know how to resolve this error:

```
Using TensorFlow backend.
/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,
 it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,
 it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,
 it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,
 it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,
 it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,
 it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "test_Cla.py", line 21, in <module>
    model = load_model('CNN.h5')
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.6/site-packages/keras/engine/saving.py", line 417, in load_model
    f = h5dict(filepath, 'r')
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.6/site-packages/keras/utils/io_utils.py", line 186, in __init__
    self.data = h5py.File(path, mode=mode)
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.6/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'CNN.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
mv: cannot stat ‘CNN.h5’: No such file or directory
cp: cannot stat ‘fp_seq’: No such file or directory
cat: fp_seq: No such file or directory
cat: fp_seq: No such file or directory
Using TensorFlow backend.
/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,
 it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,
 it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,
 it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,
 it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,
 it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,
 it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:From /scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will b
e removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and w
ill be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From /scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a fu
ture version.
Instructions for updating:
Use tf.cast instead.
2022-04-26 09:56:47.864536: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2022-04-26 09:56:47.895152: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2693670000 Hz
2022-04-26 09:56:47.895432: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x560b3e165360 executing computations on platform Host. Devices:
2022-04-26 09:56:47.895470: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
```

When I look at the end of the slurm output file, I receive the following information (run with **python3.6**):
```
1952/3000 [==================>...........] - ETA: 0s
2144/3000 [====================>.........] - ETA: 0s
2336/3000 [======================>.......] - ETA: 0s
2528/3000 [========================>.....] - ETA: 0s
2720/3000 [==========================>...] - ETA: 0s
2912/3000 [============================>.] - ETA: 0s
3000/3000 [==============================] - 1s 301us/step
testing accuracy: 0.9693333333333334
training took 906.097517s
mv: cannot stat ‘fp_seq’: No such file or directory
```

Do you know what I can do here? Suggestions are more than welcome!

**Comment by robertzeibich** [comment]
I reinstalled the env using tensorflow 1.13.1 and left the python version that comes with the tensorflow version untouched. **Seems to work now**:

```
Using TensorFlow backend.
/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,
 it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,
 it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,
 it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,
 it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,
 it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy,
 it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:From /scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will b
e removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and w
ill be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
2022-04-26 12:28:30.597995: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2022-04-26 12:28:30.609296: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2394360000 Hz
2022-04-26 12:28:30.609696: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5567ea564880 executing computations on platform Host. Devices:
2022-04-26 12:28:30.609734: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
OMP: Info #155: KMP_AFFINITY: Initial OS proc set respected: 20
OMP: Info #216: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #157: KMP_AFFINITY: 1 available OS procs
OMP: Info #158: KMP_AFFINITY: Uniform topology
OMP: Info #287: KMP_AFFINITY: topology layer "LL cache" is equivalent to "socket".
OMP: Info #287: KMP_AFFINITY: topology layer "L3 cache" is equivalent to "socket".
OMP: Info #287: KMP_AFFINITY: topology layer "L2 cache" is equivalent to "core".
OMP: Info #287: KMP_AFFINITY: topology layer "L1 cache" is equivalent to "core".
OMP: Info #192: KMP_AFFINITY: 1 socket x 1 core/socket x 1 thread/core (1 total cores)
OMP: Info #218: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #172: KMP_AFFINITY: OS proc 20 maps to socket 0 core 20 thread 0
OMP: Info #254: KMP_AFFINITY: pid 46592 tid 46592 thread 0 bound to OS proc set 20
2022-04-26 12:28:30.610088: I tensorflow/core/common_runtime/process_util.cc:71] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
WARNING:tensorflow:From /scratch/xm41/rzei0002/miniconda/conda/envs/SpliceFinder/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a fu
ture version.
Instructions for updating:
Use tf.cast instead.
OMP: Info #254: KMP_AFFINITY: pid 46592 tid 47007 thread 1 bound to OS proc set 20
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
conv1d_1 (Conv1D)            (None, 400, 50)           1850
_________________________________________________________________
flatten_1 (Flatten)          (None, 20000)             0
_________________________________________________________________
dense_1 (Dense)              (None, 100)               2000100
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 303
=================================================================
Total params: 2,002,253
Trainable params: 2,002,253
Non-trainable params: 0
_________________________________________________________________
None

   32/17708 [..............................] - ETA: 2:11OMP: Info #254: KMP_AFFINITY: pid 46592 tid 47008 thread 2 bound to OS proc set 20

  256/17708 [..............................] - ETA: 19s
  544/17708 [..............................] - ETA: 10s
  832/17708 [>.............................] - ETA: 8s
```
